#!/usr/bin/env node
const init = require('yargs-vc/init');

const BootstrapVC = require('./src/commands/bootstrap');
const LinkVC = require('./src/commands/link');
const RegisterVC = require('./src/commands/register');

init([
  BootstrapVC,
  LinkVC,
  RegisterVC
]);
